
export const SAGA_REGISTER = 'AUTH_SAGA_REGISTER';

export const SAGA_LOGIN = 'AUTH_SAGA_LOGIN';

export const PAGE_LOADING = 'AUTH_PAGE_LOADING';

export const REGISTER_COMPLETE = 'AUTH_REGISTER_COMPLETE';

export const REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const LOGIN_COMPLETE = 'AUTH_LOGIN_COMPLETE';

export const LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
