
export const SAGA_GET_GRID_LIST = 'GRID_SAGA_GET_GRID_LIST';
export const SAGA_SAVE_GRIDS = 'GRID_SAGA_SAVE_GRIDS';
export const SAGA_DELETE_GRID = 'GRID_SAGA_DELETE_GRID';

export const GET_GRID_LIST = 'GRID_GET_GRID_LIST';
export const COMPLETE_EDIT = 'GRID_COMPLETE_EDIT';
export const FAIL_EDIT = 'GRID_FAIL_EDIT';

export const PAGE_LOADING = 'GRID_PAGE_LOADING';
