
export const SAGA_GET_ITEM_LIST = 'ITEM_SAGA_GET_ITEM_LIST';
export const SAGA_GET_ITEM = 'ITEM_SAGA_GET_ITEM';
export const SAGA_ADD_ITEM = 'ITEM_SAGA_ADD_ITEM';
export const SAGA_UPDATE_ITEM = 'ITEM_SAGA_UPDATE_ITEM';
export const SAGA_DELETE_ITEM = 'ITEM_SAGA_DELETE_ITEM';
export const SAGA_REMOVE_ITEM_IMG = 'SAGA_REMOVE_ITEM_IMG';

export const GET_ITEM_LIST = 'ITEM_GET_ITEM_LIST';
export const GET_ITEM = 'ITEM_GET_ITEM';
export const COMPLETE_EDIT = 'ITEM_COMPLETE_EDIT';
export const FAIL_EDIT = 'ITEM_FAIL_EDIT';
export const COMPLETE_REMOVE_ITEM_IMG = 'COMPLETE_REMOVE_ITEM_IMG';
export const FAIL_REMOVE_ITEM_IMG = 'FAIL_REMOVE_ITEM_IMG';

export const PAGE_LOADING = 'ITEM_PAGE_LOADING';
export const UPDATE_FORM_MODE = 'ITEM_UPDATE_FORM_MODE';
