
export const SAGA_GET_SPACE_LIST = 'SPACE_SAGA_GET_SPACE_LIST';
export const SAGA_GET_SPACE = 'SPACE_SAGA_GET_SPACE';
export const SAGA_ADD_SPACE = 'SPACE_SAGA_ADD_SPACE';
export const SAGA_UPDATE_SPACE = 'SPACE_SAGA_UPDATE_SPACE';
export const SAGA_DELETE_SPACE = 'SPACE_SAGA_DELETE_SPACE';
export const SAGA_REMOVE_SPACE_IMG = 'SAGA_REMOVE_SPACE_IMG';

export const GET_SPACE_LIST = 'SPACE_GET_SPACE_LIST';
export const GET_SPACE = 'SPACE_GET_SPACE';
export const COMPLETE_EDIT = 'SPACE_COMPLETE_EDIT';
export const FAIL_EDIT = 'SPACE_FAIL_EDIT';
export const COMPLETE_REMOVE_SPACE_IMG = 'COMPLETE_REMOVE_SPACE_IMG';
export const FAIL_REMOVE_SPACE_IMG = 'FAIL_REMOVE_SPACE_IMG';

export const PAGE_LOADING = 'SPACE_PAGE_LOADING';
export const UPDATE_FORM_MODE = 'SPACE_UPDATE_FORM_MODE';
export const SET_CURRENT_SPACE_ID = 'SPACE_SET_CURRENT_SPACE_ID';
