{
 "kind": "discovery#restDescription",
 "discoveryVersion": "v1",
 "id": "bigtableclusteradmin:v1",
 "name": "bigtableclusteradmin",
 "canonicalName": "Bigtable Cluster Admin",
 "version": "v1",
 "revision": "20121021",
 "title": "Cloud Bigtable Cluster Admin API",
 "description": "This is a OnePlatform service.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://cloud.google.com/bigtable/",
 "protocol": "rest",
 "baseUrl": "https://bigtableclusteradmin.googleapis.com/v1/",
 "basePath": "/v1/",
 "rootUrl": "https://bigtableclusteradmin.googleapis.com/",
 "servicePath": "v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/bigquery.readonly": {
     "description": "View your data in Google BigQuery"
    },
    "https://www.googleapis.com/auth/cloud-bigtable.admin": {
     "description": "Administer your Cloud Bigtable tables and clusters"
    },
    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
     "description": "Administer your Cloud Bigtable clusters"
    },
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud-platform.read-only": {
     "description": "View your data across Google Cloud Platform services"
    }
   }
  }
 },
 "resources": {
  "operations": {
   "methods": {
    "cancel": {
     "id": "bigtableclusteradmin.operations.cancel",
     "path": "{+name}:cancel",
     "httpMethod": "POST",
     "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use [Operations.GetOperation][google.longrunning.Operations.GetOperation] or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operati[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-bigtable.admin",
      "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
      "https://www.googleapis.com/auth/cloud-platform"
     ]
    },
    "delete": {
     "id": "bigtableclusteradmin.operations.delete",
     "path": "{+name}",
     "httpMethod": "DELETE",
     "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-bigtable.admin",
      "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
      "https://www.googleapis.com/auth/cloud-platform"
     ]
    },
    "get": {
     "id": "bigtableclusteradmin.operations.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-bigtable.admin",
      "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
      "https://www.googleapis.com/auth/cloud-platform"
     ]
    },
    "list": {
     "id": "bigtableclusteradmin.operations.list",
     "path": "{name}",
     "httpMethod": "GET",
     "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operations co[...]",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-bigtable.admin",
      "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
      "https://www.googleapis.com/auth/cloud-platform"
     ]
    }
   }
  },
  "projects": {
   "resources": {
    "aggregated": {
     "resources": {
      "clusters": {
       "methods": {
        "list": {
         "id": "bigtableclusteradmin.projects.aggregated.clusters.list",
         "path": "{+name}/aggregated/clusters",
         "httpMethod": "GET",
         "description": "Lists all clusters in the given project, along with any zones for which cluster information could not be retrieved.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform"
         ]
        }
       }
      }
     }
    },
    "zones": {
     "methods": {
      "list": {
       "id": "bigtableclusteradmin.projects.zones.list",
       "path": "{+name}/zones",
       "httpMethod": "GET",
       "description": "Lists the supported zones for the given project.",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-bigtable.admin",
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
        "https://www.googleapis.com/auth/cloud-platform"
       ]
      }
     },
     "resources": {
      "clusters": {
       "methods": {
        "create": {
         "id": "bigtableclusteradmin.projects.zones.clusters.create",
         "path": "{+name}/clusters",
         "httpMethod": "POST",
         "description": "Creates a cluster and begins preparing it to begin serving. The returned cluster embeds as its \"current_operation\" a long-running operation which can be used to track the progress of turning up the new cluster. Immediately upon completion of this request: * The cluster will be readable via the API, with all requested attributes but no allocated resources. Until completion of the embedded operation: * Cancelling the operation will render the cluster immediately unreadab[...]",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform"
         ]
        },
        "delete": {
         "id": "bigtableclusteradmin.projects.zones.clusters.delete",
         "path": "{+name}",
         "httpMethod": "DELETE",
         "description": "Marks a cluster and all of its tables for permanent deletion in 7 days. Immediately upon completion of the request: * Billing will cease for all of the cluster's reserved resources. * The cluster's \"delete_time\" field will be set 7 days in the future. Soon afterward: * All tables within the cluster will become unavailable. Prior to the cluster's \"delete_time\": * The cluster can be recovered with a call to UndeleteCluster. * All other attempts to modify or delete the [...]",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform"
         ]
        },
        "get": {
         "id": "bigtableclusteradmin.projects.zones.clusters.get",
         "path": "{+name}",
         "httpMethod": "GET",
         "description": "Gets information about a particular cluster.",
         "scopes": [
          "https://www.googleapis.com/auth/bigquery.readonly",
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud-platform.read-only"
         ]
        },
        "patch": {
         "id": "bigtableclusteradmin.projects.zones.clusters.patch",
         "path": "{+name}",
         "httpMethod": "PATCH",
         "description": "Updates a cluster, and begins allocating or releasing resources as requested. The returned cluster embeds as its \"current_operation\" a long-running operation which can be used to track the progress of updating the cluster. Immediately upon completion of this request: * For resource types where a decrease in the cluster's allocation has been requested, billing will be based on the newly-requested level. Until completion of the embedded operation: * Cancelling the operat[...]",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform"
         ]
        },
        "update": {
         "id": "bigtableclusteradmin.projects.zones.clusters.update",
         "path": "{+name}",
         "httpMethod": "PUT",
         "description": "Updates a cluster, and begins allocating or releasing resources as requested. The returned cluster embeds as its \"current_operation\" a long-running operation which can be used to track the progress of updating the cluster. Immediately upon completion of this request: * For resource types where a decrease in the cluster's allocation has been requested, billing will be based on the newly-requested level. Until completion of the embedded operation: * Cancelling the operat[...]",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-bigtable.admin",
          "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
          "https://www.googleapis.com/auth/cloud-platform"
         ]
        }
       }
      }
     }
    }
   }
  }
 }
}
