{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "cloudidentity:v1beta1",
  "name": "cloudidentity",
  "canonicalName": "Cloud Identity",
  "version": "v1beta1",
  "revision": "0",
  "title": "Cloud Identity API",
  "description": "API for provisioning and managing identity resources.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/identity/",
  "protocol": "rest",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        }
      }
    }
  },
  "resources": {
    "groups": {
      "methods": {
        "create": {
          "id": "cloudidentity.groups.create",
          "path": "v1beta1/groups",
          "flatPath": "v1beta1/groups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a `Group`."
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Retrieves a `Group`."
        },
        "patch": {
          "id": "cloudidentity.groups.patch",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`."
        },
        "delete": {
          "id": "cloudidentity.groups.delete",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`."
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "path": "v1beta1/groups:lookup",
          "flatPath": "v1beta1/groups:lookup",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource\nname](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a `Group` by\nits `EntityKey`."
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "path": "v1beta1/groups:search",
          "flatPath": "v1beta1/groups:search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for `Group`s matching a specified query."
        },
        "list": {
          "id": "cloudidentity.groups.list",
          "path": "v1beta1/groups",
          "flatPath": "v1beta1/groups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group`s under a customer or namespace."
        }
      }
      ,
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1beta1/{+parent}/memberships",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "get": {
              "id": "cloudidentity.groups.memberships.get",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`."
            },
            "patch": {
              "id": "cloudidentity.groups.memberships.patch",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates a `Membership`."
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes a `Membership`."
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1beta1/{+parent}/memberships:lookup",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource\nname](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a\n`Membership` by its `EntityKey`."
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1beta1/{+parent}/memberships",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the `Membership`s within a `Group`."
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "searchTransitiveMemberships": {
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group."
            },
            "searchTransitiveGroups": {
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveGroups",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive groups of a member."
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "path": "v1beta1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group."
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1beta1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of a member or member\/group."
            }
          }
        }
      }
    },
    "devices": {
      "methods": {
        "create": {
          "id": "cloudidentity.devices.create",
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "httpMethod": "POST",
          "description": "Creates a device. Only company-owned device may be created."
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/devices/{devicesId}",
          "httpMethod": "GET",
          "description": "Retrieves a device."
        },
        "list": {
          "id": "cloudidentity.devices.list",
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "httpMethod": "GET",
          "description": "Lists\/Searches devices."
        },
        "patch": {
          "id": "cloudidentity.devices.patch",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/devices/{devicesId}",
          "httpMethod": "PATCH",
          "description": "Updates a device."
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/devices/{devicesId}",
          "httpMethod": "DELETE",
          "description": "Deletes a device."
        },
        "ring": {
          "id": "cloudidentity.devices.ring",
          "path": "v1beta1/{+name}:ring",
          "flatPath": "v1beta1/devices:ring",
          "httpMethod": "POST",
          "description": "Rings the device"
        },
        "lock": {
          "id": "cloudidentity.devices.lock",
          "path": "v1beta1/{+name}:lock",
          "flatPath": "v1beta1/devices:lock",
          "httpMethod": "POST",
          "description": "Locks the device, without signing out the user"
        },
        "resetPin": {
          "id": "cloudidentity.devices.resetPin",
          "path": "v1beta1/{+name}:resetPin",
          "flatPath": "v1beta1/devices:resetPin",
          "httpMethod": "POST",
          "description": "Resets the device's pin"
        },
        "wipe": {
          "id": "cloudidentity.devices.wipe",
          "path": "v1beta1/{+name}:wipe",
          "flatPath": "v1beta1/devices/{devicesId}:wipe",
          "httpMethod": "POST",
          "description": "Wipes all data on a device."
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "path": "v1beta1/{+name}:cancelWipe",
          "flatPath": "v1beta1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "description": "Cancels an unfinished device wipe.\nThis operation can be used to cancel device wipe in the gap between the\nwipe operation returning success and the device being wiped."
        },
        "getSettings": {
          "id": "cloudidentity.devices.getSettings",
          "path": "v1beta1/{+resourceId}/settings",
          "flatPath": "v1beta1/devices/{devicesId}/settings",
          "httpMethod": "GET",
          "description": "Returns the effective settings compiled for the requested entity."
        },
        "settings": {
          "id": "cloudidentity.devices.settings",
          "path": "v1beta1/{+resourceId}/settings",
          "flatPath": "v1beta1/devices/{devicesId}/settings",
          "httpMethod": "POST",
          "description": "Returns the effective settings compiled for the requested entity."
        }
      }
      ,
      "resources": {
        "deviceUsers": {
          "methods": {
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "description": "Retrieves a DeviceUser"
            },
            "list": {
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1beta1/{+parent}/deviceUsers",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers",
              "httpMethod": "GET",
              "description": "Lists\/Searches DeviceUsers."
            },
            "patch": {
              "id": "cloudidentity.devices.deviceUsers.patch",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "PATCH",
              "description": "Updates a DeviceUser."
            },
            "delete": {
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "DELETE",
              "description": "Deletes a DeviceUser. This also revokes the user's access to device data."
            },
            "collectBugReport": {
              "id": "cloudidentity.devices.deviceUsers.collectBugReport",
              "path": "v1beta1/{+name}:collectBugReport",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:collectBugReport",
              "httpMethod": "POST",
              "description": "Collects bug report on a device, which can be later downloaded from\n[Admin Console](https:\/\/admin.google.com)."
            },
            "sync": {
              "id": "cloudidentity.devices.deviceUsers.sync",
              "path": "v1beta1/{+name}:sync",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:sync",
              "httpMethod": "POST",
              "description": "Syncs the device to company's policy"
            },
            "signout": {
              "id": "cloudidentity.devices.deviceUsers.signout",
              "path": "v1beta1/{+name}:signout",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:signout",
              "httpMethod": "POST",
              "description": "Signs out the user from the device"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1beta1/{+name}:approve",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "httpMethod": "POST",
              "description": "Approves device to access user data."
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "path": "v1beta1/{+name}:block",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "httpMethod": "POST",
              "description": "Blocks device from accessing user data"
            },
            "unenroll": {
              "id": "cloudidentity.devices.deviceUsers.unenroll",
              "path": "v1beta1/{+name}:unenroll",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:unenroll",
              "httpMethod": "POST",
              "description": "Unenrolls the user from Advanced Windows Management without affecting\ntheir user account."
            },
            "wipe": {
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "path": "v1beta1/{+name}:wipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "httpMethod": "POST",
              "description": "Wipes the user's account on a device."
            },
            "cancelWipe": {
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "path": "v1beta1/{+name}:cancelWipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "description": "Cancels an unfinished user account wipe.\nThis operation can be used to cancel device wipe in the gap between the\nwipe operation returning success and the device being wiped."
            }
          }
          ,
          "resources": {
            "endpointApps": {
              "methods": {
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.endpointApps.list",
                  "path": "v1beta1/{+parent}/endpointApps",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/endpointApps",
                  "httpMethod": "GET",
                  "description": "Lists all managed apps intalled on the device."
                }
              }
            },
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1beta1/{+name}",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "GET",
                  "description": "Get client state for a device user"
                },
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1beta1/{+name}",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH",
                  "description": "Update client state for a device user"
                }
              }
            }
          }
        },
        "-": {
          "resources": {
            "deviceUsers": {
              "methods": {
                "lookupSelf": {
                  "id": "cloudidentity.devices.-.deviceUsers.lookupSelf",
                  "path": "v1beta1/devices/-/deviceUsers:lookupSelf",
                  "flatPath": "v1beta1/devices/-/deviceUsers:lookupSelf",
                  "httpMethod": "GET",
                  "description": "Looks up resource names of the DeviceUsers associated with the\ncaller's credentials, as well as the properties provided in the request."
                }
              }
            }
          }
        }
      }
    }
  },
  "basePath": ""
}