
export const OPERATION_SAVE = 'SAVE';
export const OPERATION_UPDATE = 'UPDATE';
export const OPERATION_DELETE = 'DELETE';
export const OPERATION_REMOVE_IMG = 'REMOVE_IMG';

export const FORM_EDIT_MODE= 'SPACE_EDIT_MODE';
export const FORM_READONLY_MODE= 'SPACE_READONLY_MODE';
